---
title: "Coding Wildcats 2024 Project"
subtitle: "Proposal"
author: 
  - name: "Coding Wildcats"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
import seaborn as sns
```

## Introduction and data

```{python}
#| label: load-dataset
#| message: false
```

For each data set:

- Identify the source of the data.

- State when and how it was originally collected (by the original data curator, not necessarily how you found the data).

- Write a brief description of the observations.

- Address ethical concerns about the data, if any.

Make sure to load the data and use inline code for some of this information.

## Research Question

Your research question should contain at least three variables, and should be a mix of categorical and quantitative variables. When writing a research question, please think about the following:

- What is your target population?

- Is the question original?

- Can the question be answered?

For each data set, include the following:

- A well formulated research question. (You may include more than one research question if you want to receive feedback on different ideas for your project. However, one per data set is required.)

- Statement on why this question is important.

- A description of the research topic along with a concise statement of your hypotheses on this topic.

- Identify the types of variables in your research question. Categorical? Quantitative?

## Glimpse of data

For each data set:

- Place the file containing your data in the data folder of the project repo.

- Use the `.head()` and `.info()` functions to provide a glimpse of the data set.

## Analysis plan

-   A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).

1. College Scorecard Dataset

Source: https://collegescorecard.ed.gov/data/

Data was collected from 1996-2023 by the Department of Education by institutional reporting from U.S. schools. The dataset used for this project has been modified to be uploaded to GitHub.

Observations include geographic data for each school, admission rates, institutional characteristics, enrollment, student aid, costs, and student outcomes.

No ethical concerns are present--data is collected from a department level, not individual and includes schools from across the country.

Research Question: What relationships are there between institutional characteristics and student aid, school spending and student outcomes (graduation rate, degree level, etc)?

This question represents an overview of the higher education system and its effectiveness in the United States. We hypothesize that student aid and school spending are correlated with student outcomes.

This question is important because student success is an important factor in determining their success in the workforce, as well as an indicator for future students for the quality of that education.

Variables such as school expenditure, student debt and graduate income are quantitative while variables such as degree type, institution name and city are qualitative.


```{python}
import pandas as pd
college = pd.read_csv("data/collge_data_tenative.csv")
print(college.head())
print(college.info())
```

2. Massachusetts Public Schools 2017 Records

Source: https://profiles.doe.mass.edu/

This data was collected by the Massachusetts Department of Education in 2017 from school reports given by public elementary, middle and high schools.

Observations include enrollment and graduation rates, class sizes, demographic and socioeconomic information of students, classes offered and AP testing records.

No ethical concerns are present.

Research Question: Is there a relationship between graduation rates and higher education preparation and a school's demographic makeup, funding and class size?

This question is important because the education quality for elementary through high school aged children is an important factor in their success in higher education, their careers and overall quality of life.

Variables such as school type, location, and evaluation are qualitative variables. Variables such as demographic makeup, enrollment numbers, class size and expenditure are quantitative variables.

```{python}
MA_schools = pd.read_csv("data/MA_Public_Schools_2017.csv")
print(MA_schools.head())
print(MA_schools.info())
```

3. Stroke Dataset

Source: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset

This data comes from a study published in China in 2020: Pathan, Muhammad Salman & Zhang, Jianbiao & John, Deepu & Nag, Avishek & Dev, Soumyabrata. (2020). Identifying Stroke Indicators Using Rough Sets. IEEE Access. 8. 10.1109/ACCESS.2020.3039439. 

Observations include demographic information such as age, gender, marital status, and employment status, as well as medical information such as BMI, glucose levels, smoking history, etc.

A possible ethical concern is if personal health information (PHI) could be traced to individual participants. However, data has been de-identified.

Research Question: is it possible to predict the possibility of an individual having a stroke based on their demographic information and medical history?

This question is important because identifying key risk factors of a stroke can be used for prevention and more effective monitoring of patients.

Variables such as gender, smoking status, employment status, and marital status are qualitative. Variables such as age, BMI, and glucose index are all quantitative.

```{python}
stroke = pd.read_csv("data/healthcare-dataset-stroke-data.csv")
print(stroke.head())
print(stroke.info())
```